#!/usr/bin/env python3
"""Synchronize dbt raw sources and thin base views with the live warehouse."""

from __future__ import annotations

import argparse
import json
import os
import pathlib
import re
import subprocess
import sys
import time
from dataclasses import dataclass
from datetime import datetime, timezone
from typing import Any

import duckdb
import yaml

PROJECT_DIR = pathlib.Path(__file__).resolve().parents[1]
GENERATED_MARKER = "generated by transform/scripts/sync_raw_sources.py; do not edit"
SOURCE_YAML = pathlib.Path("models/base/_raw_sources.yml")
VALID_RELATION = re.compile(r"^[a-z][a-z0-9_]*$")

LINEAGE_DESCRIPTIONS = {
    "_batch_id": "Identifier of the raw load batch that produced this row.",
    "_source_file": "Raw source file from which this row was loaded.",
    "_file_row_num": "One-based row position in the raw source file.",
    "_load_id": "Identifier of the load job that inserted this row.",
    "_loaded_at": "UTC timestamp at which the load layer inserted this row.",
    "_content_hash": "Stable hash of the raw record content used for lineage and deduplication.",
    "_payload": "Complete raw record payload retained for lineage and schema evolution.",
}


@dataclass(frozen=True)
class Column:
    name: str
    data_type: str


@dataclass(frozen=True)
class RawSource:
    name: str
    columns: tuple[Column, ...]
    rows_loaded: int
    last_loaded_at: str | None


def _shared_checkout(repo_root: pathlib.Path) -> pathlib.Path:
    common_dir = subprocess.run(
        ["git", "rev-parse", "--path-format=absolute", "--git-common-dir"],
        cwd=repo_root,
        check=True,
        capture_output=True,
        text=True,
    ).stdout.strip()
    path = pathlib.Path(common_dir)
    return path.parent if path.name == ".git" else path


def _load_deployment_env(project_dir: pathlib.Path) -> None:
    shared_root = _shared_checkout(project_dir.parent)
    sys.path.insert(0, str(shared_root / "orchestration" / "include"))
    import deployment

    deployment.load_env()
    deployment.load_env(shared_root / "orchestration" / "airflow.secrets.env")


def _connect_read_only(path: pathlib.Path, timeout_s: float = 120) -> duckdb.DuckDBPyConnection:
    deadline = time.monotonic() + timeout_s
    delay = 0.5
    while True:
        try:
            return duckdb.connect(str(path), read_only=True)
        except duckdb.IOException as exc:
            message = str(exc).lower()
            locked = "lock" in message and ("conflict" in message or "set lock" in message)
            if not locked or time.monotonic() >= deadline:
                raise
            time.sleep(min(delay, max(0.0, deadline - time.monotonic())))
            delay = min(delay * 2, 10.0)


def inspect_warehouse(path: pathlib.Path) -> list[RawSource]:
    connection = _connect_read_only(path)
    try:
        column_rows = connection.execute(
            """
            select table_name, column_name, data_type
            from information_schema.columns
            where table_schema = 'raw'
            order by table_name, ordinal_position
            """
        ).fetchall()
        load_rows = connection.execute(
            """
            select table_name,
                   cast(sum(coalesce(rows_loaded, 0)) as bigint) as rows_loaded,
                   max(loaded_at) as last_loaded_at
            from _load.files
            where status = 'loaded'
            group by table_name
            """
        ).fetchall()
    finally:
        connection.close()

    columns: dict[str, list[Column]] = {}
    for table_name, column_name, data_type in column_rows:
        columns.setdefault(str(table_name), []).append(
            Column(str(column_name), str(data_type))
        )
    loads = {
        str(table_name): (
            int(rows_loaded or 0),
            loaded_at.astimezone(timezone.utc).isoformat()
            if isinstance(loaded_at, datetime)
            else (str(loaded_at) if loaded_at is not None else None),
        )
        for table_name, rows_loaded, loaded_at in load_rows
    }

    invalid = sorted(name for name in columns if not VALID_RELATION.fullmatch(name))
    if invalid:
        raise ValueError(f"raw relation names are not valid dbt model names: {invalid}")
    return [
        RawSource(name, tuple(table_columns), *loads.get(name, (0, None)))
        for name, table_columns in sorted(columns.items())
    ]


def _load_generated_schema(project_dir: pathlib.Path) -> dict[str, Any]:
    path = project_dir / SOURCE_YAML
    if not path.is_file():
        return {}
    value = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    if not isinstance(value, dict):
        raise ValueError(f"{path} must contain a YAML mapping")
    return value


def _declared_columns(schema: dict[str, Any]) -> dict[str, list[tuple[str, str]]]:
    sources = schema.get("sources") or []
    raw = next(
        (item for item in sources if isinstance(item, dict) and item.get("name") == "raw"),
        {},
    )
    declared: dict[str, list[tuple[str, str]]] = {}
    for table in raw.get("tables") or []:
        if not isinstance(table, dict) or not table.get("name"):
            continue
        declared[str(table["name"])] = [
            (str(column.get("name")), str(column.get("data_type")))
            for column in table.get("columns") or []
            if isinstance(column, dict) and column.get("name")
        ]
    return declared


def _base_path(project_dir: pathlib.Path, source_name: str) -> pathlib.Path:
    return project_dir / "models" / "base" / f"base_{source_name}.sql"


def audit(project_dir: pathlib.Path, sources: list[RawSource]) -> dict[str, Any]:
    declared = _declared_columns(_load_generated_schema(project_dir))
    observed_names = {source.name for source in sources}
    declared_names = set(declared)
    missing_sources = sorted(observed_names - declared_names)
    missing_bases = sorted(
        source.name for source in sources if not _base_path(project_dir, source.name).is_file()
    )
    schema_drift = []
    for source in sources:
        actual = [(column.name, column.data_type) for column in source.columns]
        expected = declared.get(source.name)
        if expected is not None and expected != actual:
            schema_drift.append(
                {
                    "source": source.name,
                    "declared_columns": [
                        {"name": name, "data_type": data_type}
                        for name, data_type in expected
                    ],
                    "actual_columns": [
                        {"name": name, "data_type": data_type}
                        for name, data_type in actual
                    ],
                }
            )
    stale_sources = sorted(declared_names - observed_names)
    return {
        "ok": not (missing_sources or missing_bases or schema_drift or stale_sources),
        "sources": [
            {
                "name": source.name,
                "rows_loaded": source.rows_loaded,
                "last_loaded_at": source.last_loaded_at,
                "columns": [
                    {"name": column.name, "data_type": column.data_type}
                    for column in source.columns
                ],
            }
            for source in sources
        ],
        "missing_sources": missing_sources,
        "missing_bases": missing_bases,
        "schema_drift": schema_drift,
        "stale_sources": stale_sources,
    }


def _column_description(source_name: str, column_name: str) -> str:
    return LINEAGE_DESCRIPTIONS.get(
        column_name, f"Raw `{column_name}` value supplied by `{source_name}`."
    )


def _schema_document(sources: list[RawSource]) -> str:
    tables = []
    models = []
    for source in sources:
        columns = [
            {
                "name": column.name,
                "description": _column_description(source.name, column.name),
                "data_type": column.data_type,
            }
            for column in source.columns
        ]
        tables.append(
            {
                "name": source.name,
                "description": f"Insert-only raw records loaded for `{source.name}`.",
                "columns": columns,
            }
        )
        models.append(
            {
                "name": f"base_{source.name}",
                "description": (
                    f"Thin governed view over the `{source.name}` raw source. "
                    "Values and load lineage are preserved without semantic cleaning."
                ),
                "columns": columns,
            }
        )
    document = {
        "version": 2,
        "sources": [
            {
                "name": "raw",
                "description": "Insert-only relations written by the load layer.",
                "database": "extract",
                "schema": "raw",
                "tables": tables,
            }
        ],
        "models": models,
    }
    return f"# {GENERATED_MARKER}\n" + yaml.safe_dump(
        document, sort_keys=False, width=100
    )


def _base_sql(source: RawSource) -> str:
    selected = ",\n    ".join(f'"{column.name.replace(chr(34), chr(34) * 2)}"' for column in source.columns)
    return (
        f"-- {GENERATED_MARKER}\n"
        f"select\n    {selected}\n"
        f"from {{{{ source('raw', '{source.name}') }}}}\n"
    )


def write_all(project_dir: pathlib.Path, sources: list[RawSource]) -> list[str]:
    base_dir = project_dir / "models" / "base"
    base_dir.mkdir(parents=True, exist_ok=True)
    changed: list[str] = []
    schema_path = project_dir / SOURCE_YAML
    schema_text = _schema_document(sources)
    if not schema_path.is_file() or schema_path.read_text(encoding="utf-8") != schema_text:
        schema_path.write_text(schema_text, encoding="utf-8")
        changed.append(str(schema_path.relative_to(project_dir)))

    for source in sources:
        path = _base_path(project_dir, source.name)
        text = _base_sql(source)
        if path.is_file():
            existing = path.read_text(encoding="utf-8")
            if GENERATED_MARKER not in existing:
                continue
            if existing == text:
                continue
        path.write_text(text, encoding="utf-8")
        changed.append(str(path.relative_to(project_dir)))
    return changed


def _human_summary(result: dict[str, Any]) -> str:
    state = "clean" if result["ok"] else "drift"
    return (
        f"raw source coverage: {state}; {len(result['sources'])} source(s), "
        f"{len(result['missing_sources'])} missing declaration(s), "
        f"{len(result['missing_bases'])} missing base(s), "
        f"{len(result['schema_drift'])} schema drift(s), "
        f"{len(result['stale_sources'])} stale declaration(s)"
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--check", action="store_true", help="report drift without writing")
    mode.add_argument("--write-all", action="store_true", help="synchronize generated files")
    parser.add_argument("--json", action="store_true", help="emit machine-readable output")
    parser.add_argument("--warehouse", type=pathlib.Path)
    parser.add_argument("--project-dir", type=pathlib.Path, default=PROJECT_DIR)
    args = parser.parse_args()

    project_dir = args.project_dir.resolve()
    _load_deployment_env(project_dir)
    warehouse = (args.warehouse or pathlib.Path(os.environ["EXTRACT_WAREHOUSE"])).expanduser()
    sources = inspect_warehouse(warehouse)
    changed: list[str] = []
    if args.write_all:
        changed = write_all(project_dir, sources)
    result = audit(project_dir, sources)
    result["warehouse"] = str(warehouse)
    result["changed_files"] = changed
    if args.json:
        print(json.dumps(result, indent=2, sort_keys=True))
    else:
        print(_human_summary(result))
        for path in changed:
            print(f"updated {path}")
    if args.write_all or (args.check and args.json):
        return 0
    return 0 if result["ok"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
