{{ config(
    materialized='table',
    on_schema_change='fail',
    tags=['daily']
) }}

with ranked as (
    select
        cast(md5(to_json(struct_pack(
            source := source,
            id := id,
            fetched_at := fetched_at
        ))) as varchar) as charity_observation_key,
        cast(source as varchar) as source,
        cast(id as varchar) as id,
        cast(fetched_at as timestamp with time zone) as fetched_at,
        cast(metadata as json) as metadata,
        cast(activities as json) as activities,
        cast(beneficiaries as json) as beneficiaries,
        cast(groups as json) as groups,
        cast(officers as json) as officers,
        cast(sectors as json) as sectors,
        cast(activities1 as json) as activities1,
        cast(areaofoperations as json) as areaofoperations,
        cast(areaofoperations1 as json) as areaofoperations1,
        cast(beneficiaries1 as json) as beneficiaries1,
        cast(sectors1 as json) as sectors1,
        cast(sourceoffunds as json) as sourceoffunds,
        cast(annualreturn as json) as annualreturn,
        cast(organisationid as bigint) as organisationid,
        cast(accountid as varchar) as accountid,
        cast(name as varchar) as name,
        cast(charityregistrationnumber as varchar) as charityregistrationnumber,
        cast(websiteurl as varchar) as websiteurl,
        cast(emailaddress1 as varchar) as emailaddress1,
        cast(telephone1 as varchar) as telephone1,
        cast(fax as varchar) as fax,
        cast(postaladdresscity as varchar) as postaladdresscity,
        cast(postaladdressline1 as varchar) as postaladdressline1,
        cast(postaladdressline2 as varchar) as postaladdressline2,
        cast(postaladdresspostcode as varchar) as postaladdresspostcode,
        cast(postaladdresssuburb as varchar) as postaladdresssuburb,
        cast(streetaddresscity as varchar) as streetaddresscity,
        cast(streetaddressline1 as varchar) as streetaddressline1,
        cast(streetaddressline2 as varchar) as streetaddressline2,
        cast(streetaddresspostcode as varchar) as streetaddresspostcode,
        cast(streetaddresssuburb as varchar) as streetaddresssuburb,
        cast(charityemailaddress as varchar) as charityemailaddress,
        cast(companiesofficenumber as varchar) as companiesofficenumber,
        cast(dateregistered as timestamp with time zone) as dateregistered,
        cast(endofyeardayofmonth as bigint) as endofyeardayofmonth,
        cast(endofyearmonth as bigint) as endofyearmonth,
        cast(establishedbyparliamentact as boolean) as establishedbyparliamentact,
        cast(excemptioncomment as varchar) as excemptioncomment,
        cast(isincorporated as boolean) as isincorporated,
        cast(maoritrustboard as boolean) as maoritrustboard,
        cast(maoritrustapproved as boolean) as maoritrustapproved,
        cast(maraefunds as boolean) as maraefunds,
        cast(maraereservation as boolean) as maraereservation,
        cast(onlandunderteturewhenuamaoriact as boolean) as onlandunderteturewhenuamaoriact,
        cast(organisationaltype as varchar) as organisationaltype,
        cast(percentagespentoverseas as bigint) as percentagespentoverseas,
        cast(registrationstatus as varchar) as registrationstatus,
        cast(societyinstitution as varchar) as societyinstitution,
        cast(trusteestrust as varchar) as trusteestrust,
        cast(annualreturnduedate as timestamp with time zone) as annualreturnduedate,
        cast(grouptype as bigint) as grouptype,
        cast(mainactivityid as bigint) as mainactivityid,
        cast(mainbeneficiaryid as bigint) as mainbeneficiaryid,
        cast(mainsectorid as bigint) as mainsectorid,
        cast(othernames as varchar) as othernames,
        cast(modifiedon as timestamp with time zone) as modifiedon,
        cast(nzbnnumber as varchar) as nzbnnumber,
        cast(charitablepurpose as varchar) as charitablepurpose,
        cast(entitystructure as varchar) as entitystructure,
        cast(facebookname as varchar) as facebookname,
        cast(socialnetworkname as varchar) as socialnetworkname,
        cast(overseasoperationafrica as boolean) as overseasoperationafrica,
        cast(overseasoperationantarctica as boolean) as overseasoperationantarctica,
        cast(overseasoperationasia as boolean) as overseasoperationasia,
        cast(organisationreceivesdonationskoha as boolean) as organisationreceivesdonationskoha,
        cast(ethniccharity as boolean) as ethniccharity,
        cast(overseasoperationeurope as boolean) as overseasoperationeurope,
        cast(organisationgeneratesfundsgrantsdonationstoothers as boolean) as organisationgeneratesfundsgrantsdonationstoothers,
        cast(kaupapamaoricharityaffiliationwithiwiandorhapu as boolean) as kaupapamaoricharityaffiliationwithiwiandorhapu,
        cast(kaupapamaoricharity as boolean) as kaupapamaoricharity,
        cast(kaupapamaoricharitymarae as boolean) as kaupapamaoricharitymarae,
        cast(overseasoperationnorthamerica as boolean) as overseasoperationnorthamerica,
        cast(overseasoperationoceania as boolean) as overseasoperationoceania,
        cast(otherlegalstructure as varchar) as otherlegalstructure,
        cast(kaupapamaoricharityownership as boolean) as kaupapamaoricharityownership,
        cast(pasifikacharity as boolean) as pasifikacharity,
        cast(purposetogivegrantsanddonations as boolean) as purposetogivegrantsanddonations,
        cast(overseasoperationsouthamerica as boolean) as overseasoperationsouthamerica,
        cast(kaupapamaoricharityfocusesonoutcomesformaori as boolean) as kaupapamaoricharityfocusesonoutcomesformaori,
        cast(legalstructure as varchar) as legalstructure,
        cast(twittername as varchar) as twittername,
        cast(_batch_id as varchar) as _batch_id,
        cast(_load_id as varchar) as _load_id,
        cast(_source_file as varchar) as _source_file,
        cast(_file_row_num as bigint) as _file_row_num,
        cast(_loaded_at as timestamp with time zone) as source_loaded_at,
        cast(_content_hash as varchar) as _content_hash,
        row_number() over (
            partition by source, id, fetched_at
            order by _loaded_at desc, _source_file desc, _file_row_num desc
        ) as _dedupe_rank
    from {{ ref('base_nz_charities') }}
)

select
    charity_observation_key,
    source,
    id,
    fetched_at,
    metadata,
    activities,
    beneficiaries,
    groups,
    officers,
    sectors,
    activities1,
    areaofoperations,
    areaofoperations1,
    beneficiaries1,
    sectors1,
    sourceoffunds,
    annualreturn,
    organisationid,
    accountid,
    name,
    charityregistrationnumber,
    websiteurl,
    emailaddress1,
    telephone1,
    fax,
    postaladdresscity,
    postaladdressline1,
    postaladdressline2,
    postaladdresspostcode,
    postaladdresssuburb,
    streetaddresscity,
    streetaddressline1,
    streetaddressline2,
    streetaddresspostcode,
    streetaddresssuburb,
    charityemailaddress,
    companiesofficenumber,
    dateregistered,
    endofyeardayofmonth,
    endofyearmonth,
    establishedbyparliamentact,
    excemptioncomment,
    isincorporated,
    maoritrustboard,
    maoritrustapproved,
    maraefunds,
    maraereservation,
    onlandunderteturewhenuamaoriact,
    organisationaltype,
    percentagespentoverseas,
    registrationstatus,
    societyinstitution,
    trusteestrust,
    annualreturnduedate,
    grouptype,
    mainactivityid,
    mainbeneficiaryid,
    mainsectorid,
    othernames,
    modifiedon,
    nzbnnumber,
    charitablepurpose,
    entitystructure,
    facebookname,
    socialnetworkname,
    overseasoperationafrica,
    overseasoperationantarctica,
    overseasoperationasia,
    organisationreceivesdonationskoha,
    ethniccharity,
    overseasoperationeurope,
    organisationgeneratesfundsgrantsdonationstoothers,
    kaupapamaoricharityaffiliationwithiwiandorhapu,
    kaupapamaoricharity,
    kaupapamaoricharitymarae,
    overseasoperationnorthamerica,
    overseasoperationoceania,
    otherlegalstructure,
    kaupapamaoricharityownership,
    pasifikacharity,
    purposetogivegrantsanddonations,
    overseasoperationsouthamerica,
    kaupapamaoricharityfocusesonoutcomesformaori,
    legalstructure,
    twittername,
    _batch_id,
    _load_id,
    _source_file,
    _file_row_num,
    source_loaded_at,
    _content_hash
from ranked
where _dedupe_rank = 1
