{{ config(
    materialized='table',
    tags=['daily']
) }}

with source_rows as (
    select
        cast(source as varchar) as source_name,
        cast(id as varchar) as license_id,
        cast(fetched_at as timestamp with time zone) as observed_at,
        cast(usi as varchar) as universal_system_identifier,
        cast(call_sign as varchar) as call_sign,
        cast(service as varchar) as service,
        cast(radio_service_code as varchar) as radio_service_code,
        cast(license_status as varchar) as license_status,
        cast(license_status_text as varchar) as license_status_text,
        cast(grant_date as date) as grant_date,
        cast(expired_date as date) as expired_date,
        cast(cancellation_date as date) as cancellation_date,
        cast(effective_date as date) as effective_date,
        cast(last_action_date as date) as last_action_date,
        cast(entity_type as varchar) as entity_type,
        cast(city as varchar) as city,
        cast(state as varchar) as state,
        cast(zip_code as varchar) as zip_code,
        cast(frn as varchar) as frn,
        cast(operator_class as varchar) as operator_class,
        cast(operator_class_text as varchar) as operator_class_text,
        cast(previous_call_sign as varchar) as previous_call_sign,
        cast(previous_operator_class as varchar) as previous_operator_class,
        cast(vanity_relationship as varchar) as vanity_relationship,
        cast(is_vanity as boolean) as is_vanity,
        cast(is_upgrade as boolean) as is_upgrade,
        cast(source_file as varchar) as source_file,
        cast(file_modified as varchar) as file_modified,
        cast(pii_redacted as boolean) as pii_redacted,
        cast(_row_id as varchar) as _row_id,
        cast(_batch_id as varchar) as _batch_id,
        cast(_load_id as varchar) as _load_id,
        cast(_source_file as varchar) as _source_file,
        cast(_file_row_num as bigint) as _file_row_num,
        cast(_loaded_at as timestamp with time zone) as source_loaded_at,
        cast(_content_hash as varchar) as _content_hash
    from {{ ref('base_fcc_uls') }}
),

deduplicated as (
    select
        cast(md5(to_json(struct_pack(
            source_name := source_name,
            license_id := license_id,
            observed_at := observed_at
        ))) as varchar) as fcc_uls_license_observation_key,
        source_name,
        license_id,
        observed_at,
        universal_system_identifier,
        call_sign,
        service,
        radio_service_code,
        license_status,
        license_status_text,
        grant_date,
        expired_date,
        cancellation_date,
        effective_date,
        last_action_date,
        entity_type,
        city,
        state,
        zip_code,
        frn,
        operator_class,
        operator_class_text,
        previous_call_sign,
        previous_operator_class,
        vanity_relationship,
        is_vanity,
        is_upgrade,
        source_file,
        file_modified,
        pii_redacted,
        _row_id,
        _batch_id,
        _load_id,
        _source_file,
        _file_row_num,
        source_loaded_at,
        _content_hash
    from source_rows
    qualify row_number() over (
        partition by source_name, license_id, observed_at
        order by source_loaded_at desc, _source_file desc, _file_row_num desc
    ) = 1
)

select
    cast(fcc_uls_license_observation_key as varchar) as fcc_uls_license_observation_key,
    cast(source_name as varchar) as source_name,
    cast(license_id as varchar) as license_id,
    cast(observed_at as timestamp with time zone) as observed_at,
    cast(universal_system_identifier as varchar) as universal_system_identifier,
    cast(call_sign as varchar) as call_sign,
    cast(service as varchar) as service,
    cast(radio_service_code as varchar) as radio_service_code,
    cast(license_status as varchar) as license_status,
    cast(license_status_text as varchar) as license_status_text,
    cast(grant_date as date) as grant_date,
    cast(expired_date as date) as expired_date,
    cast(cancellation_date as date) as cancellation_date,
    cast(effective_date as date) as effective_date,
    cast(last_action_date as date) as last_action_date,
    cast(entity_type as varchar) as entity_type,
    cast(city as varchar) as city,
    cast(state as varchar) as state,
    cast(zip_code as varchar) as zip_code,
    cast(frn as varchar) as frn,
    cast(operator_class as varchar) as operator_class,
    cast(operator_class_text as varchar) as operator_class_text,
    cast(previous_call_sign as varchar) as previous_call_sign,
    cast(previous_operator_class as varchar) as previous_operator_class,
    cast(vanity_relationship as varchar) as vanity_relationship,
    cast(is_vanity as boolean) as is_vanity,
    cast(is_upgrade as boolean) as is_upgrade,
    cast(source_file as varchar) as source_file,
    cast(file_modified as varchar) as file_modified,
    cast(pii_redacted as boolean) as pii_redacted,
    cast(_row_id as varchar) as _row_id,
    cast(_batch_id as varchar) as _batch_id,
    cast(_load_id as varchar) as _load_id,
    cast(_source_file as varchar) as _source_file,
    cast(_file_row_num as bigint) as _file_row_num,
    cast(source_loaded_at as timestamp with time zone) as source_loaded_at,
    cast(_content_hash as varchar) as _content_hash
from deduplicated
