#!/usr/bin/env python3
"""Chess.com public API — per-user game archives with move-level timing.

Sector: open behavioural telemetry (session-level).

If Codeforces is the "attempt log", chess is the **session log**. Every game a
player has ever played is public, organised into monthly archives, with:
  * exact start/end timestamps  → session length, time-of-day habits
  * rating before each game     → skill trajectory at game granularity
  * time control chosen         → which "feature" the user engages with
  * result and termination      → outcome, plus *how* it ended (resign,
    timeout, abandonment — the last one is a rage-quit signal)
  * PGN with clock annotations  → **per-move time spent**, i.e. genuine
    interaction-level timing inside a session

That last one is the remarkable part. `[%clk 0:02:31.4]` tags in the PGN give
you how long a person deliberated on each individual decision. Very few public
datasets contain per-decision latency for millions of real users.

**Telemetry analogues:** monthly archive list = retention by month (a gap is
churn, a later archive is resurrection); games per day = DAU/engagement;
rating delta = progression; termination reason = failure taxonomy; time
control mix = feature adoption.

Verification status 2026-09-02: **KNOWN** — the `api.chess.com/pub/` interface
is long-stable and keyless, but I did not fetch it this session (sandbox host
restrictions). Confirm field names on first run.

**Fixed 2026-09-04**: the original config polled a single hardcoded placeholder
user (the script's own CLI fallback, `erik`) — real data, but an undeliberate,
near-inactive account (~1 game/day). Verified live 2026-09-04 against
`/pub/titled/GM`, chess.com's own titled-players directory (1,739 real
Grandmasters, keyless, no target needed), plus a couple of well-known IMs. This
now polls 751 real titled players -- the players people actually care about --
instead of one arbitrary account.

Endpoints:
  /pub/player/{u}                      profile
  /pub/player/{u}/stats                current ratings per time control
  /pub/player/{u}/games/archives       LIST of monthly archive URLs  <- start here
  /pub/player/{u}/games/{YYYY}/{MM}    every game that month, with PGN
  /pub/leaderboards                    global boards (aggregate, no target)
  /pub/titled/{title}                  ALL players holding a title (GM/IM/FM/...) —
                                        verified live 2026-09-04, 200, 1,739 GM
                                        usernames, no auth needed. This is the
                                        real "who are the best players" source;
                                        /pub/leaderboards only returns a top-50
                                        snapshot per time control.

Etiquette and terms:
  * Chess.com asks for a descriptive User-Agent with contact info and applies
    per-IP throttling. Serial requests are tolerated; parallel bursts get you
    blocked. Fetch archives one at a time.
  * Archives for **past months are immutable** — fetch once, cache forever,
    and only re-poll the current month. Re-crawling history is the main way
    people get rate-limited here.
  * Polling hundreds of players in one run multiplies the throttling risk
    accordingly: `POLITE_DELAY` applies before *every* request (2 requests per
    player with `max_months=1`), a single hung player is caught and skipped
    rather than aborting the whole run, and the DAG is scheduled once/day, not
    more often — chess archives don't need sub-daily granularity.
  * Lichess (lichess.org/api) is the fully open-source equivalent and is
    friendlier for bulk work — it streams NDJSON and explicitly supports
    exporting a user's whole game history. Prefer it if you need volume.

**See the ethics note in the catalog.** The rest of this catalog pseudonymises
by default because those sources cover ordinary users who didn't sign up to be
individually tracked. This source is different: fixed 2026-09-04 to target
chess.com's own `/pub/titled/GM` directory -- **public, professional players
competing under their real handle**, whose games, ratings, and results are
already broadcast and celebrated by chess.com itself. Hashing "hikaru" into a
meaningless token would destroy the entire point of the dataset (who is this
grandmaster, how did they do) for no privacy benefit anyone asked for.
`PSEUDONYMISE = False` here; leave it `True` for any future ordinary-user
source in this catalog.

Stdlib only.
"""
import hashlib
import json
import re
import sys
import time
import urllib.request
from datetime import datetime, timezone

BASE = "https://api.chess.com/pub"
USER_AGENT = "my-pipeline-poc/0.1 (contact: you@example.com)"
POLITE_DELAY = 0.5
PSEUDONYMISE = False

CLK = re.compile(r"\[%clk\s+(\d+):(\d{2}):(\d{2}(?:\.\d+)?)\]")


def _get(path: str):
    time.sleep(POLITE_DELAY)
    req = urllib.request.Request(f"{BASE}/{path}",
                                 headers={"User-Agent": USER_AGENT})
    with urllib.request.urlopen(req, timeout=20) as resp:
        return json.load(resp)


def _uid(username: str) -> str:
    if not PSEUDONYMISE:
        return username
    return "cc_" + hashlib.sha256(username.lower().encode()).hexdigest()[:16]


def list_archives(username: str):
    """Monthly archive URLs. The gaps in this list ARE the churn signal."""
    return _get(f"player/{username}/games/archives").get("archives", [])


def parse_move_times(pgn: str | None):
    """Extract per-move remaining clock (seconds) from PGN [%clk] tags, then
    difference them into time-spent-per-move. Returns [] if unannotated."""
    if not pgn:
        return []
    remaining = []
    for h, m, s in CLK.findall(pgn):
        remaining.append(int(h) * 3600 + int(m) * 60 + float(s))
    # even indices = one player, odd = the other; diff within each side
    spent = []
    for side in (0, 1):
        seq = remaining[side::2]
        for i in range(1, len(seq)):
            spent.append(round(seq[i - 1] - seq[i], 1))
    return spent


def fetch_month(username: str, year: int, month: int, include_pgn: bool = False):
    """All games for one user-month, normalized."""
    data = _get(f"player/{username}/games/{year}/{month:02d}")
    now = datetime.now(timezone.utc).isoformat()
    me = username.lower()
    for g in data.get("games", []):
        white, black = g.get("white") or {}, g.get("black") or {}
        is_white = (white.get("username", "").lower() == me)
        mine, theirs = (white, black) if is_white else (black, white)
        start, end = g.get("start_time"), g.get("end_time")
        times = parse_move_times(g.get("pgn"))
        yield {
            "source": "chesscom_game",
            "fetched_at": now,
            "id": g.get("uuid"),
            "user": _uid(username),
            "color": "white" if is_white else "black",
            "start": datetime.fromtimestamp(start, tz=timezone.utc).isoformat()
                     if start else None,
            "end": datetime.fromtimestamp(end, tz=timezone.utc).isoformat()
                   if end else None,
            "duration_s": (end - start) if (start and end) else None,
            "time_class": g.get("time_class"),     # bullet/blitz/rapid/daily
            "time_control": g.get("time_control"),
            "rated": g.get("rated"),
            "my_rating": mine.get("rating"),       # skill at this moment
            "opp_rating": theirs.get("rating"),
            "result": mine.get("result"),          # win / resigned / timeout...
            "opp_result": theirs.get("result"),
            "rules": g.get("rules"),
            "eco": g.get("eco"),
            "n_moves_timed": len(times),
            "median_move_time_s": (sorted(times)[len(times) // 2]
                                   if times else None),
            "max_move_time_s": max(times) if times else None,
            "pgn": g.get("pgn") if include_pgn else None,
        }


def fetch_history(username: str, max_months: int | None = None):
    """Walk every archive. Past months are immutable — cache them."""
    archives = list_archives(username)
    if max_months:
        archives = archives[-max_months:]
    for url in archives:
        y, m = url.rstrip("/").split("/")[-2:]
        yield from fetch_month(username, int(y), int(m))


# 751 real titled players (750 GMs from /pub/titled/GM, verified live
# 2026-09-04, plus IM Levy Rozman/'gothamchess' who isn't GM-titled but is
# among the most-watched chess personalities). Not curated by rating within
# the list -- chess.com's own titled-players endpoint doesn't rank them, and
# GM is already the top ~1-2% title tier.
CURATED_WATCHLIST = [
    "0blivi0usspy",
    "123lt",
    "124chess",
    "1977ivan",
    "1lifeb4",
    "1stsecond",
    "21s1s1",
    "2bf41-0",
    "777azazello777",
    "a-adly",
    "a-fier",
    "aa175",
    "aaravdenglaofficial",
    "abasovn",
    "abbasifarhassan",
    "abbasovfarid1979",
    "abdimalik_abdisalimov",
    "abhidabhi",
    "abhijeetgupta",
    "abhijeetgupta1016",
    "abhijeetonyoutube",
    "abhyak",
    "absentzest",
    "aceontheturn",
    "actorxu",
    "adananpale",
    "adaro",
    "adar_07",
    "adham_fawzy",
    "adiosabu",
    "adotand",
    "afgano29",
    "afreshlyawakenedcapybara",
    "aggy67",
    "agser",
    "ahmadzadaa",
    "ahmad_alkhatib11",
    "aibayt",
    "airgun1",
    "aksaeze",
    "akshatchandra",
    "akshayraj_kore",
    "al-mudahka",
    "alefedorov",
    "aleksa74",
    "aleksandrovaleksei",
    "aleksey_sorokin",
    "alexander-evdokimov",
    "alexanderl",
    "alexander_donchenko",
    "alexander_moskalenko",
    "alexander_zubov",
    "alexandr_predke",
    "alexchess1984",
    "alexcolovic",
    "alexeishirov",
    "alexei_kornev",
    "alexhuzman",
    "alexonischuk",
    "alexrustemov",
    "alexsur1981",
    "alextargarian",
    "alexvangog",
    "alexyermo",
    "alex_goloshchapov",
    "alex_stripunsky",
    "algeriano22",
    "alieraiseafireoozeuh",
    "alishersuleymenov",
    "allanstig",
    "allstarserious",
    "almo64",
    "alpacacheck",
    "alrayyan2022",
    "alrayyan2024",
    "aman",
    "ameetghasi100",
    "amintabatabaei",
    "amir-zaibi",
    "amirbagheri78",
    "amirreza_p",
    "anaconda1704",
    "anaconda1983",
    "ancarmaran",
    "andabata",
    "andrbaryshpolets",
    "andreikka",
    "andrei_belozerov",
    "andreystukopin",
    "androqueen",
    "andyrodri",
    "angelogm",
    "angry_twin",
    "anishgiri",
    "anishonyoutube",
    "ankit_chessneurons",
    "annawel",
    "anna_muzychuk",
    "anon219",
    "ansprvt",
    "anthonywirig",
    "antipov_mikhail_al",
    "antonshomoev",
    "antonsmirnov",
    "anton_demchenko",
    "anuar_is",
    "anurag328",
    "aoitsukibluemoon",
    "apocalyps999",
    "aquarium76",
    "aradej",
    "arambai",
    "arcticbear64",
    "arcymisie",
    "arencibia",
    "argyllprince",
    "ariancito1",
    "arjun2002",
    "arkonada50",
    "arm-akiba",
    "armenianlion",
    "aronyak1",
    "arseniy_nesterov",
    "artem_ilyin",
    "arthurguo",
    "arthurkogan",
    "artooon",
    "artur0208",
    "art_vandelay1980",
    "arvika",
    "aryamabreu",
    "aryangholami",
    "aryantari",
    "as0nchess",
    "asadlivugar",
    "aspired",
    "astralpulse",
    "atabayevsaparmyrat",
    "atalik",
    "atomrod",
    "attack2mateu",
    "attackgm",
    "attilaczebe",
    "augustomatraga",
    "austrianfalcon",
    "avantage_ru",
    "averagerecord",
    "avetik_chessmood",
    "avitalbor",
    "avolodin",
    "axves",
    "aygehovit1992",
    "azerichess",
    "azerichessss",
    "azeryahu",
    "azgm",
    "azikom",
    "azzaro25",
    "a_kandil",
    "b-man",
    "b-unit",
    "baag",
    "babegroot",
    "baby_legs",
    "bacallao2019",
    "bachira1995",
    "bacyanide",
    "badrobocop",
    "baki83",
    "bakki78",
    "baku_boulevard",
    "bancsoo",
    "bankrotten",
    "barcelona_guy",
    "bardiya06",
    "bartoszsocko",
    "barys1974",
    "barzed",
    "bashlykskiy",
    "batchuluun_tsegmed",
    "batica1984",
    "batolovic",
    "bazarov04",
    "beastslovetheprocess",
    "beca95",
    "beebucks",
    "belabadea21",
    "bentsfriend",
    "berkesferi",
    "berny643",
    "berserkwerewolf",
    "besmall",
    "bestcoacheverr",
    "bigheartpawn",
    "bilelou",
    "bilguunsu",
    "billiekimbah",
    "bilodeaua",
    "binary010",
    "birdmaster3000",
    "bkl18",
    "blagid",
    "blank-horizon",
    "blefer66",
    "blindfoldkrikor",
    "blindginger",
    "blindlast7samurai",
    "blindtakes",
    "blitzking1729",
    "blitz_expert23",
    "blueshark23",
    "bluewizzard",
    "bmochsner",
    "bmw326",
    "bobanbogosavljevic",
    "bocah_sakit",
    "bocharovd",
    "bogdandeac",
    "bonamente",
    "bonca64",
    "bonuspater18",
    "boo786",
    "boorrj",
    "borisk62",
    "bornio",
    "bosiocic",
    "bougipanula",
    "brainwolf",
    "brandonjacobson",
    "brianescalante",
    "brightthunder",
    "brrrmuda",
    "brt6209",
    "bryansmith",
    "bubacik",
    "bubi6",
    "budisavljevic",
    "buenaventuravillamayor",
    "buffy7",
    "bui2512",
    "burbur555",
    "byniolus",
    "c-25",
    "caefellion",
    "caissa12",
    "calenofatal",
    "californiadreamgirl",
    "camembert4000",
    "campanero26",
    "capoeirajogo",
    "captainjames",
    "caracternin123",
    "carlosalbornoz",
    "casper_schoppen",
    "caspiisrael",
    "cassoulet",
    "cayse",
    "ccgrandmaster",
    "cemilcan",
    "ceraunophilmera",
    "cerdasbrs",
    "chabanon",
    "chadaevnikolay",
    "champ2005",
    "charlatante",
    "charlesdobronxs28",
    "chaunceygardiner64",
    "checkbits",
    "checky2015",
    "checom",
    "chefshouse",
    "chepaschess",
    "chernobay_artem",
    "chessasuke",
    "chessawp",
    "chessbrah",
    "chessdjw",
    "chessdude",
    "chesseducation4u",
    "chessfatbear",
    "chessfreak35",
    "chessialist",
    "chessinfun2030",
    "chessintuit",
    "chessking518",
    "chesslab_singapore",
    "chesslover0108",
    "chessmagician64",
    "chessmastaflash88",
    "chessmisic",
    "chessmood",
    "chessnerdstv",
    "chessnikreg11",
    "chessonado",
    "chessonthemat007",
    "chesspanda123",
    "chessphoenix17",
    "chessqueen",
    "chesssharkz",
    "chessskool",
    "chesssplayer21",
    "chesstrainer2042",
    "chesstraining77",
    "chesswarrior7197",
    "chessweebs",
    "chesswolf1210",
    "chesswy",
    "chess_zpx",
    "chito89",
    "chopper1905",
    "chowman64",
    "christopheryoo",
    "cipy77",
    "citychess_said",
    "ckgchess",
    "classyel",
    "coach_davido",
    "cocobala",
    "cody1983",
    "colchonero64",
    "coldplace",
    "colerranmorad",
    "conquering",
    "contora",
    "contrversia",
    "copperbrain",
    "courgete",
    "crackcubano",
    "crazy",
    "crazyboy26",
    "crescentmoon2411",
    "cristhiancruzsanchez",
    "cruel_yaro",
    "cruise999",
    "cschoppen",
    "ctionescu",
    "cubitas",
    "cute_castle",
    "cyrilmarcelin",
    "d-fernandez",
    "daanbrandenburg",
    "daat",
    "daggigretarsson",
    "daika91",
    "dalmatinac101",
    "dancingheaven16",
    "dangerousattack1st",
    "danieldardha2005",
    "danielking",
    "danielnaroditsky",
    "daniel_fridman",
    "danir29",
    "danyuffa",
    "darcylima",
    "darkalekhine",
    "dark_soul98",
    "daro94",
    "davidarenas1224",
    "davidbaramidze",
    "davidgavrilescu18",
    "davidmarkosyan",
    "david_arutinian",
    "david_klein",
    "davorinkuljasevic",
    "davor_rogic",
    "dbojkov",
    "ddevreugt",
    "deadeye10",
    "dearmike",
    "debashisdebs",
    "dedic8",
    "deep306",
    "defenceboy",
    "delhigm",
    "denis_makhnyov",
    "denlaz",
    "den_kuzo",
    "desconocido04",
    "deviatkinandrey",
    "devikbronstein",
    "devonlaratt",
    "dforcen",
    "dhlt216",
    "dhoine",
    "dibyendu_barua",
    "didici",
    "dinozavr69",
    "diokletian",
    "directorron",
    "divyadeshmukh23",
    "diwi89",
    "djakovenko",
    "djojua",
    "dj_haubi",
    "dlugy",
    "dmitrymaximov",
    "dogsofwar",
    "dominguezonyoutube",
    "donkeykong3003",
    "dontstopmemeowth",
    "dorian2017",
    "dostis",
    "dr-bassem",
    "dr-cro",
    "draganbarlov",
    "dragansolak",
    "dragonflow",
    "drags95",
    "draskovicl",
    "drawdenied-twitch",
    "drblinditsky",
    "drenchev",
    "dretch",
    "drfast",
    "dropstonedp",
    "drsacrificestein",
    "drtancredi",
    "druskacik",
    "drvelja",
    "drycounty",
    "dr_alpha",
    "dr_mortimer",
    "dr_tyger",
    "duanlian",
    "dudaki",
    "dudedoel",
    "duhless",
    "dulemaster",
    "dulemudule",
    "dumbo32",
    "durarbayli",
    "dusanacns",
    "dyadya81",
    "dynamikus",
    "dynamischestrategie",
    "e-grivas",
    "eagle_2019",
    "echecsenfrance",
    "egorgeroev",
    "ehsan_ghaemmaghami",
    "el-marmalade",
    "eldax64",
    "eldur16",
    "elefante33",
    "elefante38",
    "elegance_riks",
    "elgasanov",
    "elhelvetico",
    "eliaschess1999",
    "eljanov",
    "elliotstabler",
    "ellipaehtz",
    "elprofesorsergio",
    "elshan1985",
    "eltajsafarli",
    "eltaj_safarli",
    "emilanka",
    "emiliocordova",
    "emperor87",
    "enajer77",
    "enki007",
    "erebuni91",
    "erikblomqvist",
    "ermito2020",
    "ernestofdz",
    "erwinlami",
    "eternalimprover",
    "etoilegeniale",
    "etserga",
    "eugeneperelshteyn",
    "evandro_barbosa",
    "evgchess5",
    "evgeniy_88",
    "evgeny81",
    "evgenypigusov",
    "evgenyromanov",
    "evgenysharapov",
    "evgenyt",
    "ewcchamps",
    "excellent1st",
    "e_miranda",
    "fabianocaruana",
    "fablibi",
    "fabsid",
    "fairchess_on_youtube",
    "fandorine",
    "faqade",
    "farout1364",
    "farrukh_amonatov",
    "fartobus",
    "fatupss",
    "faustinooro",
    "faustregel",
    "fccbeginner",
    "fcchelsea14",
    "federtiu",
    "fedoseev-vladimir",
    "felixblohberger",
    "feliztigriz",
    "feuerwehrmannsam",
    "fghsmn",
    "fighterman91",
    "filippov_anton",
    "firegrizzly",
    "firehand33",
    "fireheart92",
    "firouzja2003",
    "fishanick",
    "fisherchess2000",
    "fivetrick",
    "fizmat_64",
    "flaviocobolli",
    "floatingdream1",
    "floydferris",
    "flycont",
    "fmshawnrl123",
    "fodorpoti",
    "foewa98",
    "forevery0ung",
    "formerprodigy",
    "fortemaestro",
    "fosti19",
    "francygm",
    "frankieyale",
    "frederiksvane",
    "frolyanov_d",
    "frostnova",
    "ftacnikl",
    "ftorodent",
    "funo09",
    "fyall777",
    "g3god",
    "gabix_94",
    "gabrielian_artur",
    "gabuzyan_chessmood",
    "gadimbaylia",
    "gaguna",
    "gahryman",
    "gaizca",
    "gajuchess",
    "gakashchess",
    "galaxyroman",
    "galperinplaton",
    "gampr2492",
    "garcho08",
    "gareth-bale11",
    "garrykasparov",
    "gasconjr",
    "gats1",
    "gavrikov",
    "geller_jakov",
    "geminiboy",
    "gen-gutman",
    "gena217",
    "genghis_k",
    "genna1943",
    "georgegiorgadze",
    "georgescu_tiberiu",
    "georgmeier",
    "gergo85",
    "german-2826",
    "gevorg_harutjunyan",
    "ggg",
    "ggs2600",
    "gguseinov",
    "ghandeevam2003",
    "ghertneck",
    "giantslayer83",
    "giantthresher",
    "gigaquparadze",
    "gilmil",
    "ginger_gm",
    "givesalltheflow",
    "gliglu",
    "gm-andreyorlov",
    "gmakobianstl",
    "gmalex1971",
    "gmalmeida",
    "gmalsayed",
    "gmandrey64",
    "gmantic",
    "gmartin_petrov",
    "gmarturyusupovauthor",
    "gmarunchess",
    "gmashley",
    "gmasterkiller",
    "gmaxel23",
    "gmazapata",
    "gmbarbosachess",
    "gmbartek",
    "gmbellicose",
    "gmbenjaminbok",
    "gmbenjaminfinegold",
    "gmbrewchess",
    "gmcarlosaobregon",
    "gmcheparinov",
    "gmchessrob",
    "gmcorrales",
    "gmcristhian",
    "gmcyborek",
    "gmdharshsky",
    "gmdiamant",
    "gmdrh",
    "gmedmundo",
    "gmg",
    "gmgamil",
    "gmharikrishna",
    "gmhess",
    "gmhikaruontwitch",
    "gmianrogers",
    "gmizeta",
    "gmjacobaagaard",
    "gmjankovic",
    "gmjlh",
    "gmjoel",
    "gmjoey1",
    "gmjuliogranda",
    "gmkomarov",
    "gmkrikor",
    "gmlazarobruzon",
    "gmmarcelkanarek",
    "gmmarcindziuba",
    "gmmatamoros",
    "gmmelik",
    "gmmickeyadams",
    "gmmikhailkazakov",
    "gmmikiki",
    "gmmitkov",
    "gmmoranda",
    "gmmoskalenko",
    "gmnakamuracyborg",
    "gmneiksans",
    "gmneiksans-bots",
    "gmnickpert",
    "gmoratovsky",
    "gmpacman",
    "gmpanno",
    "gmpetewells",
    "gmpontuscarlsson",
    "gmrafpig",
    "gmreniergonzalez",
    "gmronbo",
    "gmsakk",
    "gmsergiobarrientos",
    "gmsolver",
    "gmsrinath",
    "gmstefanova",
    "gmszabo",
    "gmtalks_youtube",
    "gmtamaz",
    "gmtazbir",
    "gmtodorov",
    "gmtopmoves",
    "gmvallejo",
    "gmvar",
    "gmvignirvatnar",
    "gmvladimir_petkov",
    "gmvladko",
    "gmvolokitin",
    "gmwso",
    "gmyarick",
    "gmyaz",
    "gmzaven",
    "gm_aag",
    "gm_andrei_murariu",
    "gm_arman_pashikian",
    "gm_barcenilla",
    "gm_batchuluun",
    "gm_buhmann",
    "gm_crest",
    "gm_d85",
    "gm_darwinlaylo",
    "gm_dmitrij",
    "gm_donatello",
    "gm_huschenbeth",
    "gm_igor_smirnov",
    "gm_levan_pantsulaia",
    "gm_petrovich",
    "gm_rashid",
    "gm_robertomogranzini",
    "gm_shahin",
    "gm_splinter",
    "gm_yupi",
    "goanchesstrio",
    "godspeed",
    "godspeed66666",
    "godzilla099",
    "gogiametutune",
    "gogieff",
    "goingkronos",
    "goodluck06",
    "gopalgn64",
    "gorato",
    "gordima",
    "goryachkina",
    "gracefulyear",
    "grafdemontekritz",
    "grandelicious",
    "grandmaster1369",
    "grebnev_a",
    "grieve72",
    "grigorgrigorov",
    "grischuk",
    "groovykettle",
    "grukjr",
    "grzechu96",
    "gserper",
    "guachiney",
    "guardianphilip",
    "gudmundur_kjartansson",
    "guenplen",
    "guesschess_game",
    "gukeshdommaraju",
    "gundavaa89",
    "gurelediz",
    "gurevichmikhail",
    "guriempire",
    "gusanchutik",
    "gutovandrey",
    "gyapiking",
    "gyro-zepeli",
    "h4parah5",
    "halfnatty",
    "hamisandwich",
    "hamonde",
    "handplay01",
    "handszar",
    "hansen",
    "hansontwitch",
    "hanzo_hasashi1",
    "haring_batil",
    "harry_rakkel",
    "harsha_bharathakoti",
    "harutjunyan-gevorg",
    "harutyuniantigrank",
    "hasaka90",
    "hasangatin_ramil",
    "hatsummei",
    "hayhalam64",
    "heartablaze",
    "hedinn",
    "heliopsis",
    "helloworld1262",
    "hercules3000",
    "hercules64",
    "hesham-a",
    "higescha",
    "hikaru",
    "hikarunakamura",
    "hiksemi",
    "gothamchess",
]


def fetch_watchlist(usernames, max_months: int | None = 1):
    """Games for every user in `usernames`. One slow/failed player (rate
    limit, deactivated account, timeout) is logged to stderr and skipped
    rather than aborting a run covering hundreds of players."""
    for username in usernames:
        try:
            yield from fetch_history(username, max_months=max_months)
        except Exception as exc:  # noqa: BLE001 - keep the watchlist run going
            print(f"chess_archives: skipping {username!r}: {exc!r}", file=sys.stderr)


if __name__ == "__main__":
    if len(sys.argv) > 1:
        gen = fetch_watchlist(sys.argv[1:], max_months=1)
    else:
        gen = fetch_watchlist(CURATED_WATCHLIST, max_months=1)
    for rec in gen:
        print(json.dumps(rec, ensure_ascii=False))
