#!/usr/bin/env python3
"""Internet Archive Wayback CDX API — query what has been archived, and when.

Lead #32: a meta-internet dataset — you're measuring the act of preservation rather
than the content. Pairs well with Certificate Transparency (#14, also in this catalog)
for "new domain appears, gets archived, disappears" lifecycle work.

**Verified live 2026-09-03** — `web.archive.org/cdx/search/cdx?url=example.org&
matchType=domain&from=20260830&to=20260903&collapse=timestamp:8&showSkipCount=true&
output=json` returned **200, 4,579 bytes, 30 real capture records**, spanning
2026-08-30 through 2026-08-31 — inside the requested window, confirming both the date
filter and the response shape work as documented.

**Re-verified live 2026-09-04**: `matchType=domain`/`host` against any site with real
traffic (bbc.com, openai.com, whitehouse.gov, waxy.org) timed out past 25s — CDX has to
scan the entire capture history for every subdomain, which is expensive for anything
popular. `matchType=exact` against one specific URL (e.g. a homepage) stayed fast
(~1-4s) even for very high-traffic sites (bbc.com/news, nytimes.com, x.com all
responded in a few seconds). Default to `exact` and target specific pages, not whole
domains, unless the domain is genuinely small.

Endpoint: `https://web.archive.org/cdx/search/cdx?url=<url>&output=json&...`
    matchType=domain|host|prefix|exact   how broadly to match the url — prefer "exact"
                                           (see the 2026-09-04 note above)
    from=YYYYMMDD&to=YYYYMMDD              date-range filter — the reliable way to
                                           get "recent" captures (see quirks)
    collapse=timestamp:N                    dedupe captures to one per N-digit
                                           timestamp prefix (e.g. `timestamp:8` = one
                                           per day) so you don't get every near-
                                           duplicate re-crawl
    limit=N                                  cap the row count

Quirks that will cost someone an afternoon:
    * **The response is a JSON array of arrays, with the field names as the first
      row** — `[["urlkey","timestamp","original","mimetype","statuscode","digest",
      "length"], [actual, row, values, ...], ...]`. It is not a list of objects; the
      first element is a header row you must zip against the rest yourself.
    * **A negative `limit` (e.g. `limit=-2`) did not behave as "the N most recent"
      in this session** — it returned entries from 2022 while a positive-limit,
      date-ranged query for the same period returned entries from 2026. The exact
      semantics of negative limit were not fully resolved here; **use `from=`/`to=`
      for "recent captures" instead of relying on negative limit**, which is what
      this script does.
    * `original` is the archived URL **URL-encoded**, and can itself contain
      percent-encoded Unicode and even literal `<`/`>`/backslash sequences from
      malformed real-world URLs that got crawled — don't assume it's a clean URL
      ready to reuse without validation.
    * `statuscode` in the row is a **string**, and `"-"` (not a number) appears for
      revisit records that point at a prior identical capture rather than storing a
      fresh HTTP response.
    * `archive.org/wayback/available?url=...` is a different, simpler endpoint (one
      URL -> its single closest snapshot) — useful for a quick "has this been
      archived at all" check, but not for browsing capture history the way CDX does.
    * **`matchType=domain`/`host` times out on any popular site** (see the
      2026-09-04 note above) — use `matchType=exact` against specific pages when
      cycling through many high-traffic sites in one run.

Etiquette: keyless, no published rate limit for CDX specifically, but this is shared
Internet Archive infrastructure — use `collapse=` to avoid pulling near-duplicate rows,
prefer a narrow date range over an unbounded query, and use a short per-request
timeout plus per-URL error handling when polling a large watchlist so one slow site
doesn't stall or fail the whole run.

Stdlib only.
"""
import json
import sys
import urllib.parse
import urllib.request
from datetime import datetime, timedelta, timezone

USER_AGENT = "my-pipeline-poc/0.1 (contact: you@example.com)"
BASE = "https://web.archive.org/cdx/search/cdx"
REQUEST_TIMEOUT_S = 12


def _get(url):
    req = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
    with urllib.request.urlopen(req, timeout=REQUEST_TIMEOUT_S) as resp:
        return json.load(resp)


CURATED_WATCHLIST = [
    "https://www.bbc.com/news",
    "https://www.reuters.com/",
    "https://apnews.com/",
    "https://www.nytimes.com/",
    "https://www.washingtonpost.com/",
    "https://www.wsj.com/",
    "https://www.cnn.com/",
    "https://www.theguardian.com/",
    "https://www.aljazeera.com/",
    "https://www.npr.org/",
    "https://www.usatoday.com/",
    "https://www.latimes.com/",
    "https://www.cbsnews.com/",
    "https://abcnews.go.com/",
    "https://www.nbcnews.com/",
    "https://www.foxnews.com/",
    "https://www.bloomberg.com/",
    "https://www.ft.com/",
    "https://www.economist.com/",
    "https://time.com/",
    "https://www.newsweek.com/",
    "https://www.politico.com/",
    "https://thehill.com/",
    "https://www.axios.com/",
    "https://www.vox.com/",
    "https://www.buzzfeednews.com/",
    "https://www.propublica.org/",
    "https://www.independent.co.uk/",
    "https://www.telegraph.co.uk/",
    "https://www.thetimes.co.uk/",
    "https://www.mirror.co.uk/",
    "https://www.dailymail.co.uk/",
    "https://www.thesun.co.uk/",
    "https://www.metro.co.uk/",
    "https://news.sky.com/",
    "https://www.channel4.com/news",
    "https://www.spiegel.de/",
    "https://www.faz.net/",
    "https://www.sueddeutsche.de/",
    "https://www.zeit.de/",
    "https://www.bild.de/",
    "https://www.welt.de/",
    "https://www.lemonde.fr/",
    "https://www.lefigaro.fr/",
    "https://www.liberation.fr/",
    "https://www.france24.com/en/",
    "https://www.rfi.fr/en/",
    "https://www.corriere.it/",
    "https://www.repubblica.it/",
    "https://www.lastampa.it/",
    "https://elpais.com/",
    "https://www.elmundo.es/",
    "https://www.publico.pt/",
    "https://www.nu.nl/",
    "https://www.dr.dk/nyheder",
    "https://www.svt.se/nyheter",
    "https://www.nrk.no/",
    "https://yle.fi/",
    "https://www.rte.ie/news/",
    "https://www.smh.com.au/",
    "https://www.theage.com.au/",
    "https://www.abc.net.au/news",
    "https://www.news.com.au/",
    "https://www.nzherald.co.nz/",
    "https://www.stuff.co.nz/",
    "https://www.cbc.ca/news",
    "https://www.ctvnews.ca/",
    "https://www.theglobeandmail.com/",
    "https://www.scmp.com/",
    "https://www.japantimes.co.jp/",
    "https://www3.nhk.or.jp/news/",
    "https://www.straitstimes.com/",
    "https://www.channelnewsasia.com/",
    "https://www.thehindu.com/",
    "https://timesofindia.indiatimes.com/",
    "https://www.ndtv.com/",
    "https://www.hindustantimes.com/",
    "https://www.indiatoday.in/",
    "https://www.dawn.com/",
    "https://www.thejakartapost.com/",
    "https://www.bangkokpost.com/",
    "https://www.koreaherald.com/",
    "https://en.yna.co.kr/",
    "https://www.globaltimes.cn/",
    "https://www.rt.com/",
    "https://tass.com/",
    "https://www.themoscowtimes.com/",
    "https://www.haaretz.com/",
    "https://www.jpost.com/",
    "https://www.timesofisrael.com/",
    "https://www.arabnews.com/",
    "https://www.gulfnews.com/",
    "https://www.khaleejtimes.com/",
    "https://mg.co.za/",
    "https://www.news24.com/",
    "https://www.iol.co.za/",
    "https://www.dailynation.co.ke/",
    "https://punchng.com/",
    "https://www.premiumtimesng.com/",
    "https://www.folha.uol.com.br/",
    "https://oglobo.globo.com/",
    "https://www.clarin.com/",
    "https://www.lanacion.com.ar/",
    "https://www.eluniversal.com.mx/",
    "https://www.milenio.com/",
    "https://elcomercio.pe/",
    "https://www.eltiempo.com/",
    "https://www.upi.com/",
    "https://www.efe.com/",
    "https://www.dpa.com/",
    "https://www.afp.com/en",
    "https://www.xinhuanet.com/english/",
    "https://www.whitehouse.gov/",
    "https://www.congress.gov/",
    "https://www.supremecourt.gov/",
    "https://www.state.gov/",
    "https://www.defense.gov/",
    "https://www.treasury.gov/",
    "https://www.federalreserve.gov/",
    "https://www.cdc.gov/",
    "https://www.fda.gov/",
    "https://www.nih.gov/",
    "https://www.who.int/",
    "https://www.un.org/",
    "https://www.nato.int/",
    "https://europa.eu/european-union/index_en",
    "https://ec.europa.eu/info/index_en",
    "https://www.consilium.europa.eu/en/",
    "https://www.europarl.europa.eu/portal/en",
    "https://www.ecb.europa.eu/",
    "https://www.gov.uk/",
    "https://www.parliament.uk/",
    "https://www.bankofengland.co.uk/",
    "https://www.canada.ca/en.html",
    "https://www.pm.gov.au/",
    "https://www.pmo.gov.in/",
    "https://japan.kantei.go.jp/",
    "https://www.mfa.gov.cn/eng/",
    "https://www.imf.org/en/Home",
    "https://www.worldbank.org/en/home",
    "https://www.wto.org/",
    "https://www.nasa.gov/",
    "https://www.noaa.gov/",
    "https://www.esa.int/",
    "https://www.epa.gov/",
    "https://www.faa.gov/",
    "https://www.fema.gov/",
    "https://www.irs.gov/",
    "https://www.usa.gov/",
    "https://www.sec.gov/",
    "https://www.ftc.gov/",
    "https://www.fbi.gov/",
    "https://www.cia.gov/",
    "https://www.interpol.int/",
    "https://www.redcross.org/",
    "https://www.icrc.org/en",
    "https://www.unicef.org/",
    "https://www.unhcr.org/",
    "https://www.wfp.org/",
    "https://www.google.com/",
    "https://www.apple.com/",
    "https://www.microsoft.com/",
    "https://www.amazon.com/",
    "https://www.meta.com/",
    "https://www.tesla.com/",
    "https://www.nvidia.com/en-us/",
    "https://openai.com/",
    "https://www.anthropic.com/",
    "https://x.com/",
    "https://www.linkedin.com/",
    "https://www.netflix.com/",
    "https://www.spotify.com/",
    "https://github.com/",
    "https://gitlab.com/",
    "https://www.salesforce.com/",
    "https://www.oracle.com/",
    "https://www.ibm.com/",
    "https://www.intel.com/content/www/us/en/homepage.html",
    "https://www.amd.com/en.html",
    "https://www.adobe.com/",
    "https://www.samsung.com/global/",
    "https://www.sony.com/en/",
    "https://www.uber.com/",
    "https://www.airbnb.com/",
    "https://www.paypal.com/",
    "https://stripe.com/",
    "https://www.shopify.com/",
    "https://www.dropbox.com/",
    "https://slack.com/",
    "https://zoom.us/",
    "https://www.cloudflare.com/",
    "https://aws.amazon.com/",
    "https://cloud.google.com/",
    "https://azure.microsoft.com/en-us/",
    "https://www.reddit.com/",
    "https://www.pinterest.com/",
    "https://www.snapchat.com/",
    "https://www.tiktok.com/en/",
    "https://www.twitch.tv/",
    "https://www.wikipedia.org/",
    "https://www.mozilla.org/en-US/",
    "https://www.wordpress.com/",
    "https://www.ebay.com/",
    "https://www.walmart.com/",
    "https://www.target.com/",
    "https://www.bestbuy.com/",
    "https://www.alibaba.com/",
    "https://www.jd.com/",
    "https://www.baidu.com/",
    "https://www.tencent.com/en-us",
    "https://status.openai.com/",
    "https://www.githubstatus.com/",
    "https://status.cloud.google.com/",
    "https://status.aws.amazon.com/",
    "https://status.azure.com/",
    "https://status.slack.com/",
    "https://status.zoom.us/",
    "https://status.dropbox.com/",
    "https://status.stripe.com/",
    "https://status.cloudflare.com/",
    "https://status.digitalocean.com/",
    "https://www.githubstatus.com/history",
    "https://status.atlassian.com/",
    "https://status.salesforce.com/",
    "https://status.discord.com/",
    "https://status.spotify.com/",
    "https://downforeveryoneorjustme.com/",
    "https://finance.yahoo.com/",
    "https://www.marketwatch.com/",
    "https://www.cnbc.com/",
    "https://www.investing.com/",
    "https://www.nasdaq.com/",
    "https://www.nyse.com/index",
    "https://www.londonstockexchange.com/",
    "https://www.jpx.co.jp/english/",
    "https://www.hkex.com.hk/?sc_lang=en",
    "https://www.coindesk.com/",
    "https://www.coinmarketcap.com/",
    "https://www.tradingview.com/",
    "https://www.morningstar.com/",
    "https://www.barrons.com/",
    "https://seekingalpha.com/",
    "https://www.espn.com/",
    "https://www.skysports.com/",
    "https://www.bbc.com/sport",
    "https://www.uefa.com/",
    "https://www.fifa.com/",
    "https://www.olympics.com/en/",
    "https://www.nba.com/",
    "https://www.nfl.com/",
    "https://www.mlb.com/",
    "https://www.nhl.com/",
    "https://www.formula1.com/en.html",
    "https://www.wimbledon.com/",
    "https://www.rollingstone.com/",
    "https://variety.com/",
    "https://www.hollywoodreporter.com/",
    "https://deadline.com/",
    "https://www.billboard.com/",
    "https://pitchfork.com/",
    "https://www.ign.com/",
    "https://kotaku.com/",
    "https://www.gamespot.com/",
    "https://www.polygon.com/",
    "https://www.eurogamer.net/",
    "https://www.nature.com/",
    "https://www.science.org/",
    "https://en.wikipedia.org/wiki/Main_Page",
    "https://en.wikipedia.org/wiki/Special:RecentChanges",
    "https://en.wikipedia.org/wiki/Portal:Current_events",
    "https://arxiv.org/",
    "https://www.scientificamerican.com/",
    "https://www.newscientist.com/",
    "https://www.nationalgeographic.com/",
    "https://www.smithsonianmag.com/",
    "https://www.hopkinsmedicine.org/coronavirus/",
    "https://coronavirus.jhu.edu/map.html",
    "https://climate.nasa.gov/",
    "https://www.weather.gov/",
    "https://weather.com/",
    "https://earthquake.usgs.gov/",
    "https://volcano.si.edu/",
    "https://news.ycombinator.com/",
    "https://stackoverflow.com/",
    "https://www.producthunt.com/",
    "https://lobste.rs/",
    "https://www.metafilter.com/",
    "https://boingboing.net/",
    "https://slashdot.org/",
    "https://arstechnica.com/",
    "https://www.theverge.com/",
    "https://techcrunch.com/",
    "https://www.wired.com/",
    "https://www.engadget.com/",
    "https://gizmodo.com/",
    "https://mashable.com/",
    "https://www.zdnet.com/",
    "https://www.cnet.com/",
    "https://www.tomshardware.com/",
    "https://www.anandtech.com/",
    "https://9to5mac.com/",
    "https://9to5google.com/",
    "https://www.androidauthority.com/",
    "https://www.macrumors.com/",
    "https://www.theinformation.com/",
    "https://stratechery.com/",
    "https://daringfireball.net/",
    "https://simonwillison.net/",
    "https://waxy.org/",
    "https://www.thestar.com/",
    "https://www.thestar.com.my/",
    "https://www.philstar.com/",
    "https://www.inquirer.net/",
    "https://vnexpress.net/",
    "https://tuoitre.vn/",
    "https://www.kompas.com/",
    "https://www.antaranews.com/",
    "https://www.bernama.com/en/",
    "https://www.chinadaily.com.cn/",
    "https://www.people.com.cn/",
    "https://www.cctv.com/",
    "https://www.cgtn.com/",
    "https://www.aa.com.tr/en",
    "https://www.trtworld.com/",
    "https://www.hurriyetdailynews.com/",
    "https://www.presstv.ir/",
    "https://www.dailystar.com.lb/",
    "https://www.thenationalnews.com/",
    "https://www.egypttoday.com/",
    "https://www.ahram.org.eg/",
    "https://www.moroccoworldnews.com/",
    "https://www.theeastafrican.co.ke/",
    "https://www.monitor.co.ug/",
    "https://www.herald.co.zw/",
    "https://www.nation.co.ke/",
    "https://www.bundesregierung.de/breg-en",
    "https://www.elysee.fr/en/",
    "https://www.gob.mx/",
    "https://www.gov.br/pt-br",
    "https://www.gob.cl/",
    "https://www.argentina.gob.ar/",
    "https://www.gov.za/",
    "https://www.india.gov.in/",
    "https://www.china.org.cn/",
    "https://japan.go.jp/",
    "https://www.korea.net/",
    "https://www.pmo.gov.sg/",
    "https://www.gov.sg/",
    "https://www.saudi.gov.sa/",
    "https://u.ae/en",
    "https://www.gov.il/en",
    "https://www.president.gov.ua/en",
    "https://www.kremlin.ru/",
    "https://www.usnews.com/",
    "https://www.forbes.com/",
    "https://fortune.com/",
    "https://www.businessinsider.com/",
    "https://www.inc.com/",
    "https://www.fastcompany.com/",
    "https://www.chronicle.com/",
    "https://www.insidehighered.com/",
    "https://www.edweek.org/",
    "https://www.motherjones.com/",
    "https://theintercept.com/",
    "https://www.commondreams.org/",
    "https://www.nationalreview.com/",
    "https://www.breitbart.com/",
    "https://www.newsmax.com/",
    "https://www.washingtontimes.com/",
    "https://www.dailywire.com/",
    "https://reason.com/",
    "https://www.salon.com/",
    "https://www.slate.com/",
    "https://theweek.com/",
    "https://www.newyorker.com/",
    "https://harpers.org/",
    "https://www.theatlantic.com/",
    "https://www.nybooks.com/",
    "https://www.foreignaffairs.com/",
    "https://foreignpolicy.com/",
    "https://www.cfr.org/",
    "https://carnegieendowment.org/",
    "https://www.brookings.edu/",
    "https://www.rand.org/",
    "https://www.pewresearch.org/",
    "https://www.gallup.com/",
    "https://www.oecd.org/en/",
    "https://www.weforum.org/",
    "https://www.transparency.org/en",
    "https://www.amnesty.org/en/",
    "https://www.hrw.org/",
    "https://www.bbc.co.uk/weather",
    "https://www.accuweather.com/",
    "https://edition.cnn.com/",
    "https://www.reutersagency.com/en/",
    "https://www.euronews.com/",
    "https://www.dw.com/en/top-stories/s-9097",
    "https://www.voanews.com/",
    "https://www.rferl.org/",
    "https://www.aljazeera.net/",
    "https://www.skynewsarabia.com/",
    "https://timesofmalta.com/",
    "https://cyprus-mail.com/",
    "https://www.gov.uk/government/organisations/hm-treasury",
    "https://www.gov.uk/government/organisations/foreign-commonwealth-development-office",
    "https://www.gov.uk/government/organisations/home-office",
    "https://www.gov.uk/government/organisations/ministry-of-defence",
    "https://www.gov.uk/government/organisations/department-of-health-and-social-care",
    "https://www.nhs.uk/",
    "https://www.ons.gov.uk/",
    "https://www.cbo.gov/",
    "https://www.gao.gov/",
    "https://www.opm.gov/",
    "https://www.usda.gov/",
    "https://www.dol.gov/",
    "https://www.hud.gov/",
    "https://www.ed.gov/",
    "https://www.energy.gov/",
    "https://www.dhs.gov/",
    "https://www.justice.gov/",
    "https://www.commerce.gov/",
    "https://www.transportation.gov/",
    "https://www.va.gov/",
    "https://www.ssa.gov/",
    "https://www.ecdc.europa.eu/en",
    "https://www.efsa.europa.eu/en",
    "https://www.eea.europa.eu/en",
    "https://www.echa.europa.eu/",
    "https://www.imo.org/en/",
    "https://www.icao.int/",
    "https://www.iaea.org/",
    "https://www.cern.ch/",
    "https://www.qualcomm.com/",
    "https://www.cisco.com/",
    "https://www.hp.com/us-en/home.html",
    "https://www.dell.com/en-us",
    "https://www.lenovo.com/us/en/",
    "https://www.asus.com/us/",
    "https://www.acer.com/us-en/",
    "https://www.huawei.com/en/",
    "https://www.xiaomi.com/en",
    "https://www.oneplus.com/",
    "https://www.motorola.com/us/",
    "https://www.att.com/",
    "https://www.verizon.com/",
    "https://www.t-mobile.com/",
    "https://www.comcast.com/",
    "https://www.spectrum.com/",
    "https://www.docker.com/",
    "https://www.mongodb.com/",
    "https://www.redis.io/",
    "https://www.postgresql.org/",
    "https://www.python.org/",
    "https://nodejs.org/en",
    "https://go.dev/",
    "https://www.rust-lang.org/",
    "https://kotlinlang.org/",
    "https://www.docker.com/products/docker-hub/",
    "https://www.npmjs.com/",
    "https://pypi.org/",
    "https://huggingface.co/",
    "https://www.kaggle.com/",
    "https://www.figma.com/",
    "https://www.canva.com/",
    "https://www.notion.so/",
    "https://www.atlassian.com/",
    "https://www.zendesk.com/",
    "https://www.hubspot.com/",
    "https://www.squarespace.com/",
    "https://wordpress.org/",
    "https://www.wix.com/",
    "https://status.datadoghq.com/",
    "https://status.heroku.com/",
    "https://status.mongodb.com/",
    "https://www.cloudflarestatus.com/",
    "https://status.redis.com/",
    "https://status.postman.com/",
    "https://status.twilio.com/",
    "https://status.sendgrid.com/",
    "https://status.pagerduty.com/",
    "https://status.hubspot.com/",
    "https://status.zendesk.com/",
    "https://status.shopify.com/",
    "https://www.instagram-status.com/",
    "https://www.premierleague.com/",
    "https://www.laliga.com/en-GB",
    "https://www.bundesliga.com/en/",
    "https://www.legaseriea.it/en",
    "https://www.ligue1.com/en/",
    "https://www.rugbyworldcup.com/",
    "https://www.icc-cricket.com/",
    "https://www.pgatour.com/",
    "https://www.atptour.com/",
    "https://www.wtatennis.com/",
    "https://www.ufc.com/",
    "https://www.wwe.com/",
    "https://www.eurosport.com/",
    "https://www.skysports.com/football",
    "https://www.goal.com/en",
    "https://www.sportingnews.com/us",
    "https://www.si.com/",
    "https://bleacherreport.com/",
    "https://www.theathletic.com/",
    "https://www.cbssports.com/",
    "https://www.quora.com/",
    "https://www.goodreads.com/",
    "https://letterboxd.com/",
    "https://www.imdb.com/",
    "https://www.rottentomatoes.com/",
    "https://www.metacritic.com/",
    "https://www.allmusic.com/",
    "https://genius.com/",
    "https://www.discogs.com/",
    "https://www.deviantart.com/",
    "https://www.behance.net/",
    "https://dribbble.com/",
    "https://www.producthunt.com/topics/artificial-intelligence",
    "https://www.indiehackers.com/",
    "https://dev.to/",
    "https://www.freecodecamp.org/news/",
    "https://www.smashingmagazine.com/",
    "https://css-tricks.com/",
    "https://www.digitaltrends.com/",
    "https://www.pcmag.com/",
    "https://www.laptopmag.com/",
    "https://www.tweaktown.com/",
    "https://www.techradar.com/",
    "https://www.slashfilm.com/",
    "https://collider.com/",
    "https://screenrant.com/",
    "https://www.thejakartapost.com/world",
    "https://en.tempo.co/",
    "https://www.rappler.com/",
    "https://www.gmanetwork.com/news/",
    "https://tvnz.co.nz/",
    "https://www.9news.com.au/",
    "https://www.7news.com.au/",
    "https://www.skynews.com.au/",
    "https://www.cbc.ca/news/canada",
    "https://montrealgazette.com/",
    "https://torontosun.com/",
    "https://vancouversun.com/",
    "https://www.calgaryherald.com/",
    "https://ottawacitizen.com/",
    "https://www.mercurynews.com/",
    "https://www.chicagotribune.com/",
    "https://www.bostonglobe.com/",
    "https://www.seattletimes.com/",
    "https://www.denverpost.com/",
    "https://www.miamiherald.com/",
    "https://www.dallasnews.com/",
    "https://www.houstonchronicle.com/",
    "https://www.ajc.com/",
    "https://www.startribune.com/",
    "https://www.philly.com/",
    "https://www.azcentral.com/",
    "https://www.ecb.europa.eu/press/pr/date/2026/html/index.en.html",
    "https://www.imf.org/en/News",
    "https://www.bis.org/",
    "https://www.spglobal.com/en/",
    "https://www.moodys.com/",
    "https://www.fitchratings.com/",
    "https://www.msci.com/",
    "https://www.ice.com/index",
    "https://www.cmegroup.com/",
    "https://www.eurexchange.com/exchange-en/",
    "https://www.six-group.com/en/home.html",
    "https://www.asx.com.au/",
    "https://www.bseindia.com/",
    "https://www.nseindia.com/",
    "https://www.b3.com.br/en_us/",
    "https://www.jse.co.za/",
]


def fetch_recent_captures(url: str, days: int = 7, match_type: str = "exact",
                          collapse_digits: int = 8):
    """Captures of `url` in the last `days` days. collapse_digits=8 dedupes to one
    row per day (YYYYMMDD prefix); use a bigger number for finer granularity.
    match_type defaults to "exact" (one URL) -- "domain"/"host" are far slower and
    time out on any site with real traffic; use them only for genuinely small or
    rarely-archived domains."""
    now = datetime.now(timezone.utc)
    since = (now - timedelta(days=days)).strftime("%Y%m%d")
    params = {"url": url, "matchType": match_type, "from": since,
             "to": now.strftime("%Y%m%d"), "collapse": f"timestamp:{collapse_digits}",
             "output": "json"}
    doc = _get(f"{BASE}?{urllib.parse.urlencode(params)}")
    if not doc or len(doc) < 2:
        return  # header-only or empty response: no captures in this window
    header, rows = doc[0], doc[1:]
    fetched_at = now.isoformat()
    for row in rows:
        rec = dict(zip(header, row))
        yield {
            "source": "wayback_cdx",
            "fetched_at": fetched_at,
            "id": f"{rec.get('urlkey')}:{rec.get('timestamp')}",
            "watched_url": url,
            "original_url": rec.get("original"),
            "captured_at": rec.get("timestamp"),  # YYYYMMDDhhmmss
            "status_code": rec.get("statuscode"),
            "mimetype": rec.get("mimetype"),
            "digest": rec.get("digest"),
            "length": rec.get("length"),
        }


def fetch_watchlist(urls, days: int = 7, match_type: str = "exact"):
    """Captures for every URL in `urls`, one query per URL. A single slow/failed
    site (timeout, 403, etc.) is logged to stderr and skipped rather than aborting
    the whole run -- with hundreds of sites in one pass, one bad actor shouldn't
    cost every other site's data."""
    for url in urls:
        try:
            yield from fetch_recent_captures(url, days=days, match_type=match_type)
        except Exception as exc:  # noqa: BLE001 - keep the watchlist run going
            print(f"wayback_cdx: skipping {url!r}: {exc!r}", file=sys.stderr)


if __name__ == "__main__":
    if len(sys.argv) > 1:
        arg_urls = [a for a in sys.argv[1:] if not a.isdigit()]
        days_args = [int(a) for a in sys.argv[1:] if a.isdigit()]
        days = days_args[0] if days_args else 7
        gen = fetch_watchlist(arg_urls, days=days)
    else:
        gen = fetch_watchlist(CURATED_WATCHLIST, days=10)
    for rec in gen:
        print(json.dumps(rec, ensure_ascii=False))
