"""Small operator-only API client; credentials are never printed."""
import http.cookiejar
import json
import urllib.error
import urllib.request


class Client:
    def __init__(self, url: str, token: str | None = None):
        self.url = url.rstrip('/')
        self.token = token
        self.opener = urllib.request.build_opener(urllib.request.HTTPCookieProcessor(http.cookiejar.CookieJar()))

    def request(self, method, path, body=None):
        headers = {'Content-Type':'application/json'}
        if self.token:
            headers['Authorization'] = 'ApiKey ' + self.token
        req = urllib.request.Request(self.url + path, data=json.dumps(body).encode() if body is not None else None, headers=headers, method=method)
        try:
            with self.opener.open(req, timeout=120) as response:
                value = json.load(response)
        except urllib.error.HTTPError as exc:
            # Avoid echoing request bodies, connection strings, or credentials.
            raise RuntimeError(f'Lightdash {method} {path} returned HTTP {exc.code}') from None
        if value.get('status') != 'ok':
            raise RuntimeError(f'Lightdash {path} did not return success')
        return value.get('results')


def bootstrap(url: str, email: str, password: str) -> str:
    client = Client(url)
    try:
        client.request('POST','/api/v1/login', {'email': email, 'password': password})
    except RuntimeError as exc:
        if 'HTTP 401' not in str(exc):
            raise
        client.request('POST','/api/v1/user', {'firstName':'Vintage','lastName':'Administrator', 'email':email, 'password':password})
    user = client.request('GET','/api/v1/user')
    if not user.get('organizationUuid'):
        client.request('PUT','/api/v1/org',{'name':'Vintage Data'})
    result = client.request('POST','/api/v1/user/me/personal-access-tokens', {'description':'Vintage Data deployment','expiresAt':None,'autoGenerated':False})
    return result['token']
