-- generated by transform/scripts/sync_raw_sources.py; do not edit
select
    "_row_id",
    "_source",
    "_batch_id",
    "_source_file",
    "_file_row_num",
    "_dt",
    "_extract_started_at",
    "_load_id",
    "_loaded_at",
    "_content_hash",
    "_payload",
    "source",
    "id",
    "fetched_at",
    "user",
    "ts",
    "problem_rating",
    "tags",
    "verdict",
    "language"
from {{ source('raw', 'codeforces') }}
