-- generated by transform/scripts/sync_raw_sources.py; do not edit
select
    "_row_id",
    "_source",
    "_batch_id",
    "_source_file",
    "_file_row_num",
    "_dt",
    "_extract_started_at",
    "_load_id",
    "_loaded_at",
    "_content_hash",
    "_payload",
    "source",
    "id",
    "fetched_at",
    "work_type",
    "current_processing_date",
    "table",
    "publisher_updated_at",
    "ecct_work_type",
    "backlog_older_than_current_processing_date",
    "ecf_work_type"
from {{ source('raw', 'uk_legal_aid_processing') }}
