-- generated by transform/scripts/sync_raw_sources.py; do not edit
select
    "_row_id",
    "_source",
    "_batch_id",
    "_source_file",
    "_file_row_num",
    "_dt",
    "_extract_started_at",
    "_load_id",
    "_loaded_at",
    "_content_hash",
    "_payload",
    "source",
    "id",
    "fetched_at",
    "visa_type",
    "average_wait_time",
    "most_completed_within"
from {{ source('raw', 'nz_visa_wait_times') }}
