select
    "_row_id",
    "_source",
    "_batch_id",
    "_source_file",
    "_file_row_num",
    "_dt",
    "_extract_started_at",
    "_load_id",
    "_loaded_at",
    "_content_hash",
    "_payload",
    "source",
    "id",
    "fetched_at",
    json_extract_string("_payload", '$.storm_id') as "storm_id",
    json_extract_string("_payload", '$.name') as "name",
    json_extract_string("_payload", '$.basin') as "basin",
    json_extract_string("_payload", '$.classification') as "classification",
    try_cast(json_extract_string("_payload", '$.intensity_kt') as double) as "intensity_kt",
    try_cast(json_extract_string("_payload", '$.pressure_mb') as double) as "pressure_mb",
    try_cast(json_extract_string("_payload", '$.latitude') as double) as "latitude",
    try_cast(json_extract_string("_payload", '$.longitude') as double) as "longitude",
    try_cast(json_extract_string("_payload", '$.movement_direction_degrees') as double) as "movement_direction_degrees",
    try_cast(json_extract_string("_payload", '$.movement_speed_kt') as double) as "movement_speed_kt",
    try_cast(json_extract_string("_payload", '$.advisory_at') as timestamp with time zone) as "advisory_at",
    json_extract_string("_payload", '$.public_advisory_url') as "public_advisory_url",
    json_extract_string("_payload", '$.forecast_advisory_url') as "forecast_advisory_url",
    json_extract_string("_payload", '$.wind_speed_probabilities_url') as "wind_speed_probabilities_url",
    json_extract("_payload", '$.raw_storm') as "raw_storm",
    json_extract("_payload", '$.raw_response') as "raw_response"
from {{ source('raw_noaa_nhc_current_storms', 'noaa_nhc_current_storms') }}
