select
    "_row_id",
    "_source",
    "_batch_id",
    "_source_file",
    "_file_row_num",
    "_dt",
    "_extract_started_at",
    "_load_id",
    "_loaded_at",
    "_content_hash",
    "_payload",
    "source",
    "id",
    "fetched_at",
    "observation_identity",
    json_extract_string("_payload", '$.upstream_id') as "upstream_id",
    "indicator_code",
    "geography_type",
    "geography_code",
    json_extract_string("_payload", '$.parent_geography_code') as "parent_geography_code",
    json_extract_string("_payload", '$.parent_geography_name') as "parent_geography_name",
    "period_type",
    "period",
    try_cast(json_extract_string("_payload", '$.numeric_value') as double) as "numeric_value",
    json_extract_string("_payload", '$.display_value') as "display_value",
    try_cast(json_extract_string("_payload", '$.low') as double) as "low",
    try_cast(json_extract_string("_payload", '$.high') as double) as "high",
    json_extract_string("_payload", '$.comments') as "comments",
    try_cast(json_extract_string("_payload", '$.date') as timestamp with time zone) as "date",
    json_extract_string("_payload", '$.time_dimension_value') as "time_dimension_value",
    try_cast(json_extract_string("_payload", '$.time_dimension_begin') as timestamp with time zone) as "time_dimension_begin",
    try_cast(json_extract_string("_payload", '$.time_dimension_end') as timestamp with time zone) as "time_dimension_end",
    "dimensions",
    "source_url"
from {{ source('raw', 'who_gho_odata') }}
